apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkJImF1dGgiOiAiVFdGcmMybHVZVHBuYUhCZlNVOXdNSFpWZUZNMFZtNVJkVFJhY1U5a1JsQm5SbFJTZFdkdE5XTXpNalJDY0haRyIKICAgICAgICAgICAgICAgIH0KCQkJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=

type: kubernetes.io/dockerconfigjson
